### ISSUE TITLE
License and i18n

### ISSUE THREAD

**Issue by WhatzzUp** [ANovokmet/angular-holiday-planner#2]
Hey mate, 

thx for your holiday planner module works like a charm!

Just two quick questions:

1. Under which license do you publish this module? MIT?
2. Is there an i18n implementation to change weekday abbreviation?
<img width="1795" alt="Screenshot 2021-04-07 at 20 26 26" src="https://user-images.githubusercontent.com/23344282/113916032-c85d7000-97df-11eb-90c0-4631aa377a72.png">

**Comment by ANovokmet** [comment]
Hello, thanks for trying out this library.

1. Yeah the license is MIT.
2. I will whip something up in a pull request.

**Comment by ANovokmet** [comment]
Check out the demo app and `getHeaderClassFn` input, eg.
```
customGetDayHeaderFn = (date) => {
    return date.format('dd');
}
```
```
[getHeaderClassFn]="customGetDayHeaderFn"
```
