### ISSUE TITLE
Mark Weekdays

### ISSUE THREAD

**Issue by WhatzzUp** [ANovokmet/angular-holiday-planner#3]
Is it possible to mark or set a class on eg. each Friday, Monday...?
I have seen an example in your demo but have no idea how solve it

<img width="1767" alt="Screenshot 2021-04-07 at 22 16 23" src="https://user-images.githubusercontent.com/23344282/113928425-1168f080-97ef-11eb-93ed-3438fc7f7368.png">

**Comment by ANovokmet** [comment]
It is now possible, check out the demo app and `getClassFn` input.
eg.
```
customGetClassFn = (date) => {
    if(date.date() == 1)
        return 'monday';
}
```
```
[getClassFn]="customGetClassFn"
```
